### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by donavon** [pbouzakis/spak#7]
First of all, big fan of spåK. Thanks. 

My issue, however, is running tests on a module that uses `App.localize`. I'm getting the following error:

```
Error: Can not return App.instance(). App.run must be invoked first.
```

I've followed the docs and added the following to my `test/support/setup.js`:

``` js
import { TestApp } from "spak/providers";
TestApp.run();
```

I was hoping that this was enough to get the default implementation of `App.localize`, which would be perfect.

Any thoughts on how to get this working?

**Comment by donavon** [comment]
Closing. The issue was that I was invoking the component from outside of mocha's `it`. I moved my code around and it now works. Thx @pbouzakis for helping me debug this.

**Comment by pbouzakis** [comment]
Anytime buddy :)
